### ISSUE TITLE
Uncaught TypeError: Date.parseDate is not a function

### ISSUE THREAD

**Issue by jasoncarty** [Zalmoxisus/momentjs-datetimepicker#1]
Getting the above error in Chrome. Reference to line 694 in the code. jquery.datetimepicker.js:694

**Comment by zalmoxisus** [comment]
Hey @jasoncarty. Could you please specify how do you initialize the datetime picker? As momentjs format fiffers from that used in the original datetimepicker.
I use it in production with:

```
el.datetimepicker({
            format: 'X', //unixtime
            formatTime: 'LT'
});
```

**Comment by jasoncarty** [comment]
Hi @Zalmoxisus, I use this to initiate the datatime picker:

``` coffeescript
$('.datetimepicker').datetimepicker({
      {dateFormat: 'yy-mm-dd'}
    });
```

I suppose its dateFormat thats incorrect.

**Comment by jasoncarty** [comment]
Hmm, nope. That still raises an error.

**Comment by zalmoxisus** [comment]
@jasoncarty, it seems that you just mistyped the object param (have double '{{').
By fixing this, it works as expected: https://jsfiddle.net/u8xt3ddf/

**Comment by jasoncarty** [comment]
Hi @Zalmoxisus, I'm sorry. I clumsily converted my coffeescript into javascript. My implementation is correct, otherwise I would get a syntax error.

If you have a look at your jsfiddle again, choose a date from the datetimepicker and then when you click outside (to remove the picker from the screen), the error shows in the console.

<img width="1372" alt="screen shot 2015-08-12 at 22 10 56" src="https://cloud.githubusercontent.com/assets/2494691/9235443/0f007668-413f-11e5-8163-e07d6cec6743.png">

**Comment by zalmoxisus** [comment]
@jasoncarty, good catch! I didn't get it as I use inline DateTimePicker.
